### ISSUE TITLE
[BUG] Problems Panel is unresponsive after opening the scratch options.

### ISSUE THREAD

**Issue by 1superchip** [decompme/decomp.me#1157]
Problems Panel is unresponsive after opening the scratch options.

1. Open a scratch
2. Go to the options panel. The page seems to reload when opening it.
3. Attempt to click on the Problems handle.
4. The problems panel will not respond.

The problems panel should respond when clicking it.

https://cdn.discordapp.com/attachments/897066363951128590/1220738748162117703/20240322-1419-01.8846801.mp4?ex=6610088d&is=65fd938d&hm=75cb7d2e137251cfba8ce264eb110bdd21db7c56f64257736afb05bbde8c19e0&

https://cdn.discordapp.com/attachments/897066363951128590/1220769113262260234/20240322-1617-52.9619414.mp4?ex=661024d5&is=65fdafd5&hm=ca30d0d35d7d566aa81bd37702cb7aaa25f5a3a81bc11124b55a5b1826a36200&

https://decomp.me/scratch/PdEX4

 - OS: Windows
 - Browser Edge

 - Device: iPhone 13
 - OS: iOS 16.3.1
 - Browser Safari

**Comment by mkst** [comment]
```
fd9d1056-2f8c52c7a5805f7b.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'minimumSize')
    at eg.resizeViews (4060-73be6f435ba6f25e.js:26:27159)
    at Object.resize (4060-73be6f435ba6f25e.js:26:35703)
    at onClick (page-5844f88db2f8536d.js:1:17210)
    at Object.aS (fd9d1056-2f8c52c7a5805f7b.js:1:71789)
    at aN (fd9d1056-2f8c52c7a5805f7b.js:1:71943)
    at fd9d1056-2f8c52c7a5805f7b.js:1:138604
    at sw (fd9d1056-2f8c52c7a5805f7b.js:1:138703)
    at sS (fd9d1056-2f8c52c7a5805f7b.js:1:139117)
    at fd9d1056-2f8c52c7a5805f7b.js:1:145260
    at oK (fd9d1056-2f8c52c7a5805f7b.js:1:92840)
```
