### ISSUE TITLE
Error running asm-differ

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#220]
https://decomp.me/scratch/KRxsJ

**Comment by ethteck** [comment]
```
Traceback (most recent call last):
  File "/var/www/decomp.me/repo/backend/coreapp/asm_diff_wrapper.py", line 143, in diff
    display = asm_differ.Display(basedump, mydump, config)
  File "/var/www/decomp.me/repo/backend/asm_differ/diff.py", line 2620, in __init__
    self.base_lines = process(basedump, config)
  File "/var/www/decomp.me/repo/backend/asm_differ/diff.py", line 1847, in process
    original = process_ppc_reloc(reloc_row, original)
  File "/var/www/decomp.me/repo/backend/asm_differ/diff.py", line 1687, in process_ppc_reloc
    assert any(
AssertionError: unknown relocation type '                       30: R_PPC_REL14 lbl_8017D700' for line 'bne     30'
```

**Comment by ethteck** [comment]
This has since been fixed, or at least I don't think it's easily reproducible atm. We can re-open if need be.
